### ISSUE TITLE
Unable to run program from cloned branch.

### ISSUE THREAD

**Issue by thriller2910** [JapaneseFrog/blue-ball-game#1]
When I clone the main branch to run the game there are assets missing, so the game does not run.

**Comment by JapaneseFrog** [comment]
I am terribly sorry for the grevious damage that Thomas Keig has caused. His absolute huberence is his downfall and although he says he will fix it all, he is too angry to do it!! He has serious issues and is a detriment to the project. Fear not Thriller, I will fix it all in no time, and there will soon be a new pre-release

**Comment by thomaskeig** [comment]
shut up thrill boy. closing this before any more havoc ensues
